<?php

return [
    'app' => [
        'title' => 'Основные',
        'desc' => 'Основные настройки приложения.',
        'icon' => 'fas fa-cube',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'app_name',
                'label' => 'Название сайта',
                'rules' => 'required|min:2|max:50',
                'class' => '',
                'value' => 'Laravel Starter',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'app_description',
                'label' => 'Описание сайта',
                'rules' => 'required',
                'class' => '',
                'value' => 'Laravel Starter - это модульный проект-стартер на Laravel.',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'footer_text',
                'label' => 'Текст футера',
                'rules' => 'required|min:2',
                'class' => '',
                'value' => '<a href="mailto:kanboto.myktybek@gmail.com" class="text-muted">Разработано с ♥ Kanbodows</a>',
            ],
            [
                'type' => 'checkbox',
                'data' => 'text',
                'name' => 'show_copyright',
                'label' => 'Показывать копирайт',
                'rules' => 'nullable',
                'class' => '',
                'value' => '1',
            ],
        ],
    ],
    'email' => [
        'title' => 'Почта',
        'desc' => 'Настройки электронной почты',
        'icon' => 'fas fa-envelope',

        'elements' => [
            [
                'type' => 'email',
                'data' => 'string',
                'name' => 'email',
                'label' => 'Email адрес',
                'rules' => 'required|email',
                'class' => '',
                'value' => 'info@example.com',
            ],
        ],
    ],
    'social' => [
        'title' => 'Социальные сети',
        'desc' => 'Ссылки на социальные сети и онлайн-профили.',
        'icon' => 'fas fa-users',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'website_url',
                'label' => 'Адрес сайта',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'facebook_url',
                'label' => 'Facebook',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'twitter_url',
                'label' => 'Twitter',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'instagram_url',
                'label' => 'Instagram',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'youtube_url',
                'label' => 'Youtube',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'linkedin_url',
                'label' => 'LinkedIn',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'whatsapp_url',
                'label' => 'WhatsApp',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'messenger_url',
                'label' => 'Messenger',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
        ],
    ],
    'meta' => [
        'title' => 'Мета-теги',
        'desc' => 'Мета-данные приложения',
        'icon' => 'fa-solid fa-earth-asia',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_site_name',
                'label' => 'Название сайта (мета)',
                'rules' => 'required',
                'class' => '',
                'value' => 'Laravel Starter',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_description',
                'label' => 'Описание (мета)',
                'rules' => 'required',
                'class' => '',
                'value' => 'Laravel Starter - это модульный проект-стартер на Laravel.',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_keyword',
                'label' => 'Ключевые слова (мета)',
                'rules' => 'nullable',
                'class' => '',
                'value' => 'Laravel, CMS, веб-приложение',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_image',
                'label' => 'Изображение (мета)',
                'rules' => 'required',
                'class' => '',
                'value' => 'img/default_banner.jpg',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_fb_app_id',
                'label' => 'Facebook App ID',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_twitter_site',
                'label' => 'Twitter аккаунт сайта',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_twitter_creator',
                'label' => 'Twitter аккаунт автора',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
            ],
        ],
    ],
    'analytics' => [
        'title' => 'Аналитика',
        'desc' => 'Настройки аналитики',
        'icon' => 'fas fa-chart-line',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'google_analytics',
                'label' => 'Google Analytics (gtag)',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
                'help' => 'Вставьте только идентификатор измерения потока Google Analytics.',
            ],
        ],
    ],
    'custom_css' => [
        'title' => 'Пользовательский код',
        'desc' => 'Область для пользовательского кода',
        'icon' => 'fa-solid fa-file-code',

        'elements' => [
            [
                'type' => 'textarea',
                'data' => 'string',
                'name' => 'custom_css_block',
                'label' => 'Пользовательский CSS',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
                'help' => 'Вставьте код в это поле.',
                'display' => 'raw',
            ],
        ],
    ],
];
